export const countries = [
  { countryCode: '+93', code: 'AF', text: 'Afghanistan  (+93)' },
  { countryCode: '+358', code: 'AX', text: 'Åland Islands  (+358)' },
  { countryCode: '+355', code: 'AL', text: 'Albania  (+355)' },
  { countryCode: '+213', code: 'DZ', text: 'Algeria  (+213)' },
  { countryCode: '+1', code: 'AS', text: 'American Samoa  (+1)' },
  { countryCode: '+376', code: 'AD', text: 'Andorra  (+376)' },
  { countryCode: '+244', code: 'AO', text: 'Angola  (+244)' },
  { countryCode: '+1', code: 'AI', text: 'Anguilla  (+1)' },
  { countryCode: '+1', code: 'AG', text: 'Antigua and Barbuda  (+1)' },
  { countryCode: '+54', code: 'AR', text: 'Argentina  (+54)' },
  { countryCode: '+374', code: 'AM', text: 'Armenia  (+374)' },
  { countryCode: '+297', code: 'AW', text: 'Aruba  (+297)' },
  { countryCode: '+6211', code: 'AU', text: 'Australia  (+61)' },
  { countryCode: '+43', code: 'AT', text: 'Austria  (+43)' },
  { countryCode: '+994', code: 'AZ', text: 'Azerbaijan  (+994)' },
  { countryCode: '+1', code: 'BS', text: 'Bahamas  (+1)' },
  { countryCode: '+973', code: 'BH', text: 'Bahrain  (+973)' },
  { countryCode: '+880', code: 'BD', text: 'Bangladesh  (+880)' },
  { countryCode: '+1', code: 'BB', text: 'Barbados  (+1)' },
  { countryCode: '+375', code: 'BY', text: 'Belarus  (+375)' },
  { countryCode: '+32', code: 'BE', text: 'Belgium  (+32)' },
  { countryCode: '+501', code: 'BZ', text: 'Belize  (+501)' },
  { countryCode: '+229', code: 'BJ', text: 'Benin  (+229)' },
  { countryCode: '+1', code: 'BM', text: 'Bermuda  (+1)' },
  { countryCode: '+975', code: 'BT', text: 'Bhutan  (+975)' },
  { countryCode: '+591', code: 'BO', text: 'Bolivia  (+591)' },
  { countryCode: '+387', code: 'BA', text: 'Bosnia and Herzegovina  (+387)' },
  { countryCode: '+267', code: 'BW', text: 'Botswana  (+267)' },
  { countryCode: '+55', code: 'BR', text: 'Brazil  (+55)' },
  {
    countryCode: '+24689',
    code: 'IO',
    text: 'British Indian Ocean Territory  (+246)',
  },
  { countryCode: '+1', code: 'VG', text: 'British Virgin Islands  (+1)' },
  { countryCode: '+673', code: 'BN', text: 'Brunei  (+673)' },
  { countryCode: '+359', code: 'BG', text: 'Bulgaria  (+359)' },
  { countryCode: '+2261', code: 'BF', text: 'Burkina Faso  (+226)' },
  { countryCode: '+257', code: 'BI', text: 'Burundi  (+257)' },
  { countryCode: '+855', code: 'KH', text: 'Cambodia  (+855)' },
  { countryCode: '+237', code: 'CM', text: 'Cameroon  (+237)' },
  { countryCode: '+1', code: 'CA', text: 'Canada  (+1)' },
  { countryCode: '+238', code: 'CV', text: 'Cape Verde  (+238)' },
  { countryCode: '+599', code: 'BQ', text: 'Caribbean Netherlands  (+599)' },
  { countryCode: '+1', code: 'KY', text: 'Cayman Islands  (+1)' },
  { countryCode: '+236', code: 'CF', text: 'Central African Republic  (+236)' },
  { countryCode: '+235', code: 'TD', text: 'Chad  (+235)' },
  { countryCode: '+56', code: 'CL', text: 'Chile  (+56)' },
  { countryCode: '+86', code: 'CN', text: 'China  (+86)' },
  { countryCode: '+61', code: 'CX', text: 'Christmas Island  (+61)' },
  {
    countryCode: '+61',
    code: 'CC',
    text:
      'Cocos' +
      // ' (Keeling)' +
      ' Islands  (+61)',
  },
  { countryCode: '+57', code: 'CO', text: 'Colombia  (+57)' },
  { countryCode: '+269', code: 'KM', text: 'Comoros  (+269)' },
  {
    countryCode: '+243',
    code: 'CD',
    text: 'Democratic Republic Congo  (+243)',
  },
  { countryCode: '+242', code: 'CG', text: 'Republic of Congo  (+242)' },
  { countryCode: '+682', code: 'CK', text: 'Cook Islands  (+682)' },
  { countryCode: '+506', code: 'CR', text: 'Costa Rica  (+506)' },
  { countryCode: '+225', code: 'CI', text: "Côte d'Ivoire  (+225)" },
  { countryCode: '+385', code: 'HR', text: 'Croatia  (+385)' },
  { countryCode: '+53', code: 'CU', text: 'Cuba  (+53)' },
  { countryCode: '+599', code: 'CW', text: 'Curaçao  (+599)' },
  { countryCode: '+357', code: 'CY', text: 'Cyprus  (+357)' },
  { countryCode: '+420', code: 'CZ', text: 'Czech Republic  (+420)' },
  { countryCode: '+45', code: 'DK', text: 'Denmark  (+45)' },
  { countryCode: '+253', code: 'DJ', text: 'Djibouti  (+253)' },
  { countryCode: '+1', code: 'DM', text: 'Dominica  (+1)' },
  { countryCode: '+1', code: 'DO', text: 'Dominican Republic  (+1)' },
  { countryCode: '+670', code: 'TL', text: 'East Timor  (+670)' },
  { countryCode: '+593', code: 'EC', text: 'Ecuador  (+593)' },
  { countryCode: '+20', code: 'EG', text: 'Egypt  (+20)' },
  { countryCode: '+503', code: 'SV', text: 'El Salvador  (+503)' },
  { countryCode: '+240', code: 'GQ', text: 'Equatorial Guinea  (+240)' },
  { countryCode: '+291', code: 'ER', text: 'Eritrea  (+291)' },
  { countryCode: '+372', code: 'EE', text: 'Estonia  (+372)' },
  { countryCode: '+251', code: 'ET', text: 'Ethiopia  (+251)' },
  { countryCode: '+500', code: 'FK', text: 'Falkland Islands   (+500)' },
  { countryCode: '+298', code: 'FO', text: 'Faroe Islands  (+298)' },
  { countryCode: '+679', code: 'FJ', text: 'Fiji  (+679)' },
  { countryCode: '+358', code: 'FI', text: 'Finland  (+358)' },
  { countryCode: '+33', code: 'FR', text: 'France  (+33)' },
  { countryCode: '+594', code: 'GF', text: 'French Guiana  (+594)' },
  { countryCode: '+689', code: 'PF', text: 'French Polynesia  (+689)' },
  { countryCode: '+241', code: 'GA', text: 'Gabon  (+241)' },
  { countryCode: '+220', code: 'GM', text: 'Gambia  (+220)' },
  { countryCode: '+995', code: 'GE', text: 'Georgia  (+995)' },
  { countryCode: '+49', code: 'DE', text: 'Germany  (+49)' },
  { countryCode: '+233', code: 'GH', text: 'Ghana  (+233)' },
  { countryCode: '+350', code: 'GI', text: 'Gibraltar  (+350)' },
  { countryCode: '+30', code: 'GR', text: 'Greece  (+30)' },
  { countryCode: '+299', code: 'GL', text: 'Greenland  (+299)' },
  { countryCode: '+1', code: 'GD', text: 'Grenada  (+1)' },
  { countryCode: '+590', code: 'GP', text: 'Guadeloupe  (+590)' },
  { countryCode: '+1', code: 'GU', text: 'Guam  (+1)' },
  { countryCode: '+502', code: 'GT', text: 'Guatemala  (+502)' },
  { countryCode: '+44', code: 'GG', text: 'Guernsey  (+44)' },
  { countryCode: '+224', code: 'GN', text: 'Guinea Conakry  (+224)' },
  { countryCode: '+245', code: 'GW', text: 'Guinea-Bissau  (+245)' },
  { countryCode: '+592', code: 'GY', text: 'Guyana  (+592)' },
  { countryCode: '+509', code: 'HT', text: 'Haiti  (+509)' },
  {
    countryCode: '+672',
    code: 'HM',
    text: 'Heard Island and McDonald Islands  (+672)',
  },
  { countryCode: '+504', code: 'HN', text: 'Honduras  (+504)' },
  { countryCode: '+852', code: 'HK', text: 'Hong Kong  (+852)' },
  { countryCode: '+36', code: 'HU', text: 'Hungary  (+36)' },
  { countryCode: '+354', code: 'IS', text: 'Iceland  (+354)' },
  { countryCode: '+91', code: 'IN', text: 'India  (+91)' },
  { countryCode: '+62', code: 'ID', text: 'Indonesia  (+62)' },
  { countryCode: '+98', code: 'IR', text: 'Iran  (+98)' },
  { countryCode: '+964', code: 'IQ', text: 'Iraq  (+964)' },
  { countryCode: '+353', code: 'IE', text: 'Ireland  (+353)' },
  { countryCode: '+44', code: 'IM', text: 'Isle of Man  (+44)' },
  { countryCode: '+972', code: 'IL', text: 'Israel  (+972)' },
  { countryCode: '+39', code: 'IT', text: 'Italy  (+39)' },
  { countryCode: '+1', code: 'JM', text: 'Jamaica  (+1)' },
  { countryCode: '+81', code: 'JP', text: 'Japan  (+81)' },
  { countryCode: '+44', code: 'JE', text: 'Jersey  (+44)' },
  { countryCode: '+962', code: 'JO', text: 'Jordan  (+962)' },
  { countryCode: '+7', code: 'KZ', text: 'Kazakhstan  (+7)' },
  { countryCode: '+254', code: 'KE', text: 'Kenya  (+254)' },
  { countryCode: '+686', code: 'KI', text: 'Kiribati  (+686)' },
  { countryCode: '+965', code: 'KW', text: 'Kuwait  (+965)' },
  { countryCode: '+996', code: 'KG', text: 'Kyrgyzstan  (+996)' },
  { countryCode: '+856', code: 'LA', text: 'Laos  (+856)' },
  { countryCode: '+371', code: 'LV', text: 'Latvia  (+371)' },
  { countryCode: '+961', code: 'LB', text: 'Lebanon  (+961)' },
  { countryCode: '+266', code: 'LS', text: 'Lesotho  (+266)' },
  { countryCode: '+231', code: 'LR', text: 'Liberia  (+231)' },
  { countryCode: '+218', code: 'LY', text: 'Libya  (+218)' },
  { countryCode: '+423', code: 'LI', text: 'Liechtenstein  (+423)' },
  { countryCode: '+370', code: 'LT', text: 'Lithuania  (+370)' },
  { countryCode: '+352', code: 'LU', text: 'Luxembourg  (+352)' },
  { countryCode: '+853', code: 'MO', text: 'Macau  (+853)' },
  { countryCode: '+389', code: 'MK', text: 'Macedonia  (+389)' },
  { countryCode: '+261', code: 'MG', text: 'Madagascar  (+261)' },
  { countryCode: '+265', code: 'MW', text: 'Malawi  (+265)' },
  { countryCode: '+60', code: 'MY', text: 'Malaysia  (+60)' },
  { countryCode: '+960', code: 'MV', text: 'Maldives  (+960)' },
  { countryCode: '+223', code: 'ML', text: 'Mali  (+223)' },
  { countryCode: '+356', code: 'MT', text: 'Malta  (+356)' },
  { countryCode: '+692', code: 'MH', text: 'Marshall Islands  (+692)' },
  { countryCode: '+596', code: 'MQ', text: 'Martinique  (+596)' },
  { countryCode: '+222', code: 'MR', text: 'Mauritania  (+222)' },
  { countryCode: '+230', code: 'MU', text: 'Mauritius  (+230)' },
  { countryCode: '+262', code: 'YT', text: 'Mayotte  (+262)' },
  { countryCode: '+52', code: 'MX', text: 'Mexico  (+52)' },
  { countryCode: '+691', code: 'FM', text: 'Micronesia  (+691)' },
  { countryCode: '+373', code: 'MD', text: 'Moldova  (+373)' },
  { countryCode: '+377', code: 'MC', text: 'Monaco  (+377)' },
  { countryCode: '+976', code: 'MN', text: 'Mongolia  (+976)' },
  { countryCode: '+382', code: 'ME', text: 'Montenegro  (+382)' },
  { countryCode: '+1', code: 'MS', text: 'Montserrat  (+1)' },
  { countryCode: '+212', code: 'MA', text: 'Morocco  (+212)' },
  { countryCode: '+258', code: 'MZ', text: 'Mozambique  (+258)' },
  { countryCode: '+95', code: 'MM', text: 'Myanmar (Burma)  (+95)' },
  { countryCode: '+264', code: 'NA', text: 'Namibia  (+264)' },
  { countryCode: '+674', code: 'NR', text: 'Nauru  (+674)' },
  { countryCode: '+977', code: 'NP', text: 'Nepal  (+977)' },
  { countryCode: '+31', code: 'NL', text: 'Netherlands  (+31)' },
  { countryCode: '+687', code: 'NC', text: 'New Caledonia  (+687)' },
  { countryCode: '+64', code: 'NZ', text: 'New Zealand  (+64)' },
  { countryCode: '+505', code: 'NI', text: 'Nicaragua  (+505)' },
  { countryCode: '+227', code: 'NE', text: 'Niger  (+227)' },
  { countryCode: '+234', code: 'NG', text: 'Nigeria  (+234)' },
  { countryCode: '+683', code: 'NU', text: 'Niue  (+683)' },
  { countryCode: '+672', code: 'NF', text: 'Norfolk Island  (+672)' },
  { countryCode: '+850', code: 'KP', text: 'North Korea  (+850)' },
  { countryCode: '+1', code: 'MP', text: 'Northern Mariana Islands  (+1)' },
  { countryCode: '+47', code: 'NO', text: 'Norway  (+47)' },
  { countryCode: '+968', code: 'OM', text: 'Oman  (+968)' },
  { countryCode: '+92', code: 'PK', text: 'Pakistan  (+92)' },
  { countryCode: '+680', code: 'PW', text: 'Palau  (+680)' },
  { countryCode: '+970', code: 'PS', text: 'Palestinian Territories  (+970)' },
  { countryCode: '+507', code: 'PA', text: 'Panama  (+507)' },
  { countryCode: '+675', code: 'PG', text: 'Papua New Guinea  (+675)' },
  { countryCode: '+595', code: 'PY', text: 'Paraguay  (+595)' },
  { countryCode: '+51', code: 'PE', text: 'Peru  (+51)' },
  { countryCode: '+63', code: 'PH', text: 'Philippines  (+63)' },
  { countryCode: '+48', code: 'PL', text: 'Poland  (+48)' },
  { countryCode: '+351', code: 'PT', text: 'Portugal  (+351)' },
  { countryCode: '+1', code: 'PR', text: 'Puerto Rico  (+1)' },
  { countryCode: '+974', code: 'QA', text: 'Qatar  (+974)' },
  { countryCode: '+262', code: 'RE', text: 'Réunion  (+262)' },
  { countryCode: '+40', code: 'RO', text: 'Romania  (+40)' },
  { countryCode: '+7', code: 'RU', text: 'Russia  (+7)' },
  { countryCode: '+250', code: 'RW', text: 'Rwanda  (+250)' },
  { countryCode: '+590', code: 'BL', text: 'Saint Barthélemy  (+590)' },
  { countryCode: '+290', code: 'SH', text: 'Saint Helena  (+290)' },
  { countryCode: '+1', code: 'KN', text: 'St. Kitts  (+1)' },
  { countryCode: '+1', code: 'LC', text: 'St. Lucia  (+1)' },
  { countryCode: '+590', code: 'MF', text: 'Saint Martin  (+590)' },
  {
    countryCode: '+508',
    code: 'PM',
    text: 'Saint Pierre and Miquelon  (+508)',
  },
  { countryCode: '+1', code: 'VC', text: 'St. Vincent  (+1)' },
  { countryCode: '+685', code: 'WS', text: 'Samoa  (+685)' },
  { countryCode: '+378', code: 'SM', text: 'San Marino  (+378)' },
  { countryCode: '+239', code: 'ST', text: 'São Tomé and Príncipe  (+239)' },
  { countryCode: '+966', code: 'SA', text: 'Saudi Arabia  (+966)' },
  { countryCode: '+221', code: 'SN', text: 'Senegal  (+221)' },
  { countryCode: '+381', code: 'RS', text: 'Serbia  (+381)' },
  { countryCode: '+248', code: 'SC', text: 'Seychelles  (+248)' },
  { countryCode: '+232', code: 'SL', text: 'Sierra Leone  (+232)' },
  { countryCode: '+65', code: 'SG', text: 'Singapore  (+65)' },
  { countryCode: '+1', code: 'SX', text: 'Sint Maarten  (+1)' },
  { countryCode: '+421', code: 'SK', text: 'Slovakia  (+421)' },
  { countryCode: '+386', code: 'SI', text: 'Slovenia  (+386)' },
  { countryCode: '+677', code: 'SB', text: 'Solomon Islands  (+677)' },
  { countryCode: '+252', code: 'SO', text: 'Somalia  (+252)' },
  { countryCode: '+27', code: 'ZA', text: 'South Africa  (+27)' },
  {
    countryCode: '+500',
    code: 'GS',
    text: 'South Georgia and the South Sandwich Islands  (+500)',
  },
  { countryCode: '+82', code: 'KR', text: 'South Korea  (+82)' },
  { countryCode: '+211', code: 'SS', text: 'South Sudan  (+211)' },
  { countryCode: '+34', code: 'ES', text: 'Spain  (+34)' },
  { countryCode: '+94', code: 'LK', text: 'Sri Lanka  (+94)' },
  { countryCode: '+249', code: 'SD', text: 'Sudan  (+249)' },
  { countryCode: '+597', code: 'SR', text: 'Suriname  (+597)' },
  { countryCode: '+47', code: 'SJ', text: 'Svalbard and Jan Mayen  (+47)' },
  { countryCode: '+268', code: 'SZ', text: 'Swaziland  (+268)' },
  { countryCode: '+46', code: 'SE', text: 'Sweden  (+46)' },
  { countryCode: '+41', code: 'CH', text: 'Switzerland  (+41)' },
  { countryCode: '+963', code: 'SY', text: 'Syria  (+963)' },
  { countryCode: '+886', code: 'TW', text: 'Taiwan  (+886)' },
  { countryCode: '+992', code: 'TJ', text: 'Tajikistan  (+992)' },
  { countryCode: '+255', code: 'TZ', text: 'Tanzania  (+255)' },
  { countryCode: '+66', code: 'TH', text: 'Thailand  (+66)' },
  { countryCode: '+228', code: 'TG', text: 'Togo  (+228)' },
  { countryCode: '+690', code: 'TK', text: 'Tokelau  (+690)' },
  { countryCode: '+676', code: 'TO', text: 'Tonga  (+676)' },
  { countryCode: '+1', code: 'TT', text: 'Trinidad/Tobago  (+1)' },
  { countryCode: '+216', code: 'TN', text: 'Tunisia  (+216)' },
  { countryCode: '+90', code: 'TR', text: 'Turkey  (+90)' },
  { countryCode: '+993', code: 'TM', text: 'Turkmenistan  (+993)' },
  { countryCode: '+1', code: 'TC', text: 'Turks and Caicos Islands  (+1)' },
  { countryCode: '+688', code: 'TV', text: 'Tuvalu  (+688)' },
  { countryCode: '+1', code: 'VI', text: 'U.S. Virgin Islands  (+1)' },
  { countryCode: '+256', code: 'UG', text: 'Uganda  (+256)' },
  { countryCode: '+380', code: 'UA', text: 'Ukraine  (+380)' },
  { countryCode: '+971', code: 'AE', text: 'United Arab Emirates  (+971)' },
  { countryCode: '+44', code: 'GB', text: 'United Kingdom  (+44)' },
  { countryCode: '+1', code: 'US', text: 'United States  (+1)' },
  { countryCode: '+598', code: 'UY', text: 'Uruguay  (+598)' },
  { countryCode: '+998', code: 'UZ', text: 'Uzbekistan  (+998)' },
  { countryCode: '+678', code: 'VU', text: 'Vanuatu  (+678)' },
  { countryCode: '+379', code: 'VA', text: 'Vatican City  (+379)' },
  { countryCode: '+58', code: 'VE', text: 'Venezuela  (+58)' },
  { countryCode: '+84', code: 'VN', text: 'Vietnam  (+84)' },
  { countryCode: '+681', code: 'WF', text: 'Wallis and Futuna  (+681)' },
  { countryCode: '+212', code: 'EH', text: 'Western Sahara  (+212)' },
  { countryCode: '+967', code: 'YE', text: 'Yemen  (+967)' },
  { countryCode: '+260', code: 'ZM', text: 'Zambia  (+260)' },
  { countryCode: '+263', code: 'ZW', text: 'Zimbabwe  (+263)' },
];
